Fix guard macro conflicts with system headers
This resolves some compile errors on FreeBSD where the `guards.h` header
is included before `stdlib.h`, leading to errors like the following:
```
ld: error: duplicate symbol: __ERROR__XX_NEVER_USE_CALLOC__
>>> defined at stdlib.h:97 (/usr/include/stdlib.h:97)
>>>            locking.o:(__ERROR__XX_NEVER_USE_CALLOC__)
>>> defined at stdlib.h:97 (/usr/include/stdlib.h:97)
>>>            timefunc.o:(.bss+0x90)

ld: error: duplicate symbol: __ERROR__XX_NEVER_USE_MALLOC__
>>> defined at stdlib.h:105 (/usr/include/stdlib.h:105)
>>>            locking.o:(__ERROR__XX_NEVER_USE_MALLOC__)
>>> defined at stdlib.h:105 (/usr/include/stdlib.h:105)
>>>            timefunc.o:(.bss+0x98)
```